name: Build Asuswrt-Modx

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'target to build'
        options:
        - RT-MIR3G
        - RT-MIR3P
        - RT-MIR4A
        - RT-RM2100
        - RT-R2100
        - RT-NEWIFI2
        - RT-XYC3
        - RT-NEWIFI3
        - RT-JDC1
        - RT-HIWIFI4
        - RT-E8820S
        - RT-A040WQ
        - RT-MSG1500
        - RT-RS1200P
      uploadanon:
        type: boolean
        description: 'upload firmware to anonfiles'
        default: 'false'
env:
  REPOSITORY_URL: https://github.com/stkuroneko/asuswrt-modx.git
  WORK_PATH: /opt/asuswrt-modx
  TIME_ZONE: Asia/Shanghai
  FIRMWARE_PATH: /opt/firmwares
jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v3
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo dpkg --add-architecture i386
        sudo dpkg -l | awk '/ii  lib.*deb.sury.org/ {gsub(/:.*/, s, $2); print $2}' | xargs apt show -a | awk '/Package:/ {p=$2} /APT-Sources: .*focal\/main/ {print p"/focal"}' | sudo xargs eatmydata apt install --allow-downgrades
        sudo apt update
        sudo apt-get -y --no-install-recommends install libncurses5 libncurses5-dev m4 bison gawk flex libstdc++6-4.4-dev g++-multilib g++
        sudo apt-get -y --no-install-recommends install gengetopt git gitk zlib1g-dev autoconf autopoint libtool shtool autogen mtd-utils intltool sharutils
        sudo apt-get -y --no-install-recommends install docbook-xsl-* libstdc++5 texinfo dos2unix xsltproc binutils u-boot-tools device-tree-compiler python
        sudo apt-get -y --no-install-recommends install qemu gperf liblzo2-dev uuid-dev build-essential lzma-dev liblzma-dev lzma patch cmake intltool yodl yodl-doc
        sudo apt-get -y --no-install-recommends install libglib2.0-dev gtk-doc-tools libc6-i386 lib32stdc++6 lib32z1 libelf1:i386 lib32ncurses5 libc6-dev-i386 libstdc++6:i386
        sudo timedatectl set-timezone "$TIME_ZONE"
    - name: Clone source code
      run: |
        git clone --depth=1 $REPOSITORY_URL $WORK_PATH
    - name: Build
      run: |
        sudo cp -f scripts/build.sh $WORK_PATH/build.sh
        cd $WORK_PATH
        sudo chmod 777 ./build.sh
        bash ./build.sh ${{ github.event.inputs.target }}
        #sudo make ${{ github.event.inputs.target }}
    - name: Organize firmware files
      run: |
        mkdir -p $FIRMWARE_PATH/
        cd $WORK_PATH/release/src-ra-5010/image
        for firmwarefile in $(ls *.trx)
        do sudo mv $firmwarefile $FIRMWARE_PATH/$firmwarefile
        done
        cd $FIRMWARE_PATH
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "STATUS=success" >> $GITHUB_ENV
    - name : Upload packages
      uses: actions/upload-artifact@main
      if: env.STATUS == 'success'
      with:
        name: Asuswrt-packages
        path: ${{ env.FIRMWARE }}
    - name: Upload firmware to anonfiles
      if: env.STATUS == 'success' && github.event.inputs.uploadanon == 'true'
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer anon --no-progress ${FIRMWARE} 2>&1 | tee anonfile.log
        echo "::warning file=anonfile.com::$(cat anonfile.log | grep -o -E "https?://[a-zA-Z0-9\.\/_&=@$%?~#-]*")"
    - name: Remove obsolete firmwares on artifacts
      uses: c-hive/gha-remove-artifacts@v1.3.0
      if: env.STATUS == 'success'
      with:
        age: '1 day'
        skip-recent: 5
